-- Autogenerated preprocess sql file
delete from programstageinstance_messageconversation;
delete from programinstancecomments;
delete from programinstanceaudit;
delete from datavalueaudit;
delete from trackedentitydatavalueaudit;
delete from trackedentityattributevalueaudit;
delete from programstageinstance_messageconversation;
delete from dataapprovalaudit;
delete from interpretation_comments;
delete from interpretationcomment;
delete from messageconversation_messages;
delete from messageconversation_usermessages;
delete from messageconversation;
--NTD
--anonymize trackers 
--anonymize all tracker
update programinstance as rand set geometry=null, organisationunitid=(select organisationunitid from organisationunit ORDER BY RANDOM()+rand.organisationunitid limit 1) where programinstanceid in ( select psi.programinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('(', ''', 'u', 'G', 'C', 'V', 'V', 'm', 'e', '3', 'C', '4', 'e', ''', ',', ' ', ''', 'N', 'H', 'y', '3', '9', 'q', 'E', 'l', '1', 'b', 'c', ''', ',', ' ', ''', 'K', 'H', 'D', 'E', 'r', 'S', 'O', 'F', 'm', 'y', '5', ''', ',', ' ', ''', 'd', 'I', 'r', '4', 'O', 't', 'N', 'c', 'v', 'M', 'w', ''', ',', ' ', ''', 'H', 'n', 'A', '4', 'S', 'U', 'O', 'a', 'T', 'i', 'j', ''', ')'));
update programstageinstance as rand set geometry=null, coordinates='', organisationunitid=(select organisationunitid from organisationunit ORDER BY RANDOM()+rand.organisationunitid limit 1) where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('(', ''', 'u', 'G', 'C', 'V', 'V', 'm', 'e', '3', 'C', '4', 'e', ''', ',', ' ', ''', 'N', 'H', 'y', '3', '9', 'q', 'E', 'l', '1', 'b', 'c', ''', ',', ' ', ''', 'K', 'H', 'D', 'E', 'r', 'S', 'O', 'F', 'm', 'y', '5', ''', ',', ' ', ''', 'd', 'I', 'r', '4', 'O', 't', 'N', 'c', 'v', 'M', 'w', ''', ',', ' ', ''', 'H', 'n', 'A', '4', 'S', 'U', 'O', 'a', 'T', 'i', 'j', ''', ')'));
update trackedentityinstance as rand set geometry=null, organisationunitid=(select organisationunitid from organisationunit ORDER BY RANDOM()+rand.organisationunitid limit 1) where trackedentityinstanceid in ( select ps.trackedentityinstanceid  from programinstance ps inner join program p on p.programid=ps.programid where p.uid in ('(', ''', 'u', 'G', 'C', 'V', 'V', 'm', 'e', '3', 'C', '4', 'e', ''', ',', ' ', ''', 'N', 'H', 'y', '3', '9', 'q', 'E', 'l', '1', 'b', 'c', ''', ',', ' ', ''', 'K', 'H', 'D', 'E', 'r', 'S', 'O', 'F', 'm', 'y', '5', ''', ',', ' ', ''', 'd', 'I', 'r', '4', 'O', 't', 'N', 'c', 'v', 'M', 'w', ''', ',', ' ', ''', 'H', 'n', 'A', '4', 'S', 'U', 'O', 'a', 'T', 'i', 'j', ''', ')'));
update trackedentityprogramowner as rand set organisationunitid=(select organisationunitid from organisationunit ORDER BY RANDOM()+rand.organisationunitid limit 1) where trackedentityinstanceid in (select trackedentityinstanceid from  program where uid in ('(', ''', 'u', 'G', 'C', 'V', 'V', 'm', 'e', '3', 'C', '4', 'e', ''', ',', ' ', ''', 'N', 'H', 'y', '3', '9', 'q', 'E', 'l', '1', 'b', 'c', ''', ',', ' ', ''', 'K', 'H', 'D', 'E', 'r', 'S', 'O', 'F', 'm', 'y', '5', ''', ',', ' ', ''', 'd', 'I', 'r', '4', 'O', 't', 'N', 'c', 'v', 'M', 'w', ''', ',', ' ', ''', 'H', 'n', 'A', '4', 'S', 'U', 'O', 'a', 'T', 'i', 'j', ''', ')'));
---coordinates
UPDATE trackedentityattributevalue set value = '46.232889,6.13426' where trackedentityinstanceid 
in ( select ps.trackedentityinstanceid  from programinstance ps 
inner join program p on p.programid=ps.programid 
where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij')) and trackedentityinstanceid in (select trackedentityattributeid from trackedentityattribute where valuetype like 'COORDINATE'); 
UPDATE trackedentityattributevalue set value='46.232889,6.13426' where trackedentityattributeid in (select trackedentityattributeid from trackedentityattribute where valuetype='COORDINATE') and trackedentityattributeid in (select trackedentityattributeid from trackedentityattribute inner join trackedentityinstance tei on tei.trackedentityinstanceid=trackedentityinstanceid inner join trackedentitytype tet on tet.trackedentitytypeid=tei.trackedentitytypeid inner join program p on tet.trackedentitytypeid=p.trackedentitytypeid where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij') );
---email
UPDATE trackedentityattributevalue set value = 'user@example.com' where trackedentityinstanceid 
in ( select ps.trackedentityinstanceid  from programinstance ps 
inner join program p on p.programid=ps.programid 
where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij')) and trackedentityinstanceid in (select trackedentityattributeid from trackedentityattribute where valuetype like 'EMAIL'); 
UPDATE trackedentityattributevalue set value='user@example.com' where trackedentityattributeid in (select trackedentityattributeid from trackedentityattribute where valuetype='EMAIL') and trackedentityattributeid in (select trackedentityattributeid from trackedentityattribute inner join trackedentityinstance tei on tei.trackedentityinstanceid=trackedentityinstanceid inner join trackedentitytype tet on tet.trackedentitytypeid=tei.trackedentitytypeid inner join program p on tet.trackedentitytypeid=p.trackedentitytypeid where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij') );
---PHONE_NUMBER
UPDATE trackedentityattributevalue set value = '+100001' where trackedentityinstanceid 
in ( select ps.trackedentityinstanceid  from programinstance ps 
inner join program p on p.programid=ps.programid 
where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij')) and trackedentityinstanceid in (select trackedentityattributeid from trackedentityattribute where valuetype like 'PHONE_NUMBER'); 
UPDATE trackedentityattributevalue set value='+100001' where trackedentityattributeid in (select trackedentityattributeid from trackedentityattribute where valuetype='PHONE_NUMBER') and trackedentityattributeid in (select trackedentityattributeid from trackedentityattribute inner join trackedentityinstance tei on tei.trackedentityinstanceid=trackedentityinstanceid inner join trackedentitytype tet on tet.trackedentitytypeid=tei.trackedentitytypeid inner join program p on tet.trackedentitytypeid=p.trackedentitytypeid where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij') );
;DO
$$DECLARE
 c CURSOR FOR SELECT * FROM trackedentityattributevalue where trackedentityinstanceid 
in ( select ps.trackedentityinstanceid  from programinstance ps 
inner join program p on p.programid=ps.programid 
where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij')) and trackedentityinstanceid in 
(select trackedentityinstanceid from trackedentityinstance where uid in ('oTvXfEywjT3', 'n8E6WIyAwcC', 'DwZNiXy5Daz', 'FHw1NKy0PWY', 'eQtZaLIO3XU', 'na3ZJRtjpGH', 'HkBG3DVELBM', 'sKBh0kazOCk', 'AAkZm4ZxFw7', 'ENRjVGxVL6l', 'aBaYLJryaMr'))and trackedentityinstanceid in (select trackedentityattributeid from trackedentityattribute where valuetype like 'EMAIL'); 
 x trackedentityattributevalue;
 i integer := 1;
BEGIN
 OPEN c;
 LOOP
 FETCH c INTO x;
 EXIT WHEN NOT FOUND;
 UPDATE trackedentityattributevalue SET value = '' || (i WHERE CURRENT OF c) || 'user@example.com';
 i := i + 1;
END LOOP;
END;$$;;
;DO
$$DECLARE
 c CURSOR FOR SELECT * FROM trackedentityattributevalue where trackedentityinstanceid 
in ( select ps.trackedentityinstanceid  from programinstance ps 
inner join program p on p.programid=ps.programid 
where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij')) and trackedentityinstanceid in 
(select trackedentityinstanceid from trackedentityinstance where uid in ('oTvXfEywjT3', 'n8E6WIyAwcC', 'DwZNiXy5Daz', 'FHw1NKy0PWY', 'eQtZaLIO3XU', 'na3ZJRtjpGH', 'HkBG3DVELBM', 'sKBh0kazOCk', 'AAkZm4ZxFw7', 'ENRjVGxVL6l', 'aBaYLJryaMr'))and trackedentityinstanceid in (select trackedentityattributeid from trackedentityattribute where valuetype like 'EMAIL'); 
 x trackedentityattributevalue;
 i integer := 1;
BEGIN
 OPEN c;
 LOOP
 FETCH c INTO x;
 EXIT WHEN NOT FOUND;
 UPDATE trackedentityattributevalue SET value = '' || (i WHERE CURRENT OF c) || 'user@example.com';
 i := i + 1;
END LOOP;
END;$$;;
;DO
$$DECLARE
 c CURSOR FOR SELECT * FROM trackedentityattributevalue teav inner join trackedentityinstance tei on tei.trackedentityinstanceid=teav.trackedentityinstanceid inner join trackedentitytype tet on tet.trackedentitytypeid=tei.trackedentitytypeid inner join program p on tet.trackedentitytypeid=p.trackedentitytypeid where teav.trackedentityattributeid in (select trackedentityattributeid from trackedentityattribute where valuetype='PHONE_NUMBER'); and p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij'); 
 x trackedentityattributevalue;
 i integer := 1;
BEGIN
 OPEN c;
 LOOP
 FETCH c INTO x;
 EXIT WHEN NOT FOUND;
 UPDATE trackedentityattributevalue SET value = (i WHERE CURRENT OF c) || '+100001';
 i := i + 1;
END LOOP;
END;$$;;
;DO
$$DECLARE
 c CURSOR FOR SELECT * FROM trackedentityattributevalue where trackedentityinstanceid 
in ( select ps.trackedentityinstanceid  from programinstance ps 
inner join program p on p.programid=ps.programid 
where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij')) and trackedentityinstanceid in 
(select trackedentityinstanceid from trackedentityinstance where uid in ('oTvXfEywjT3', 'n8E6WIyAwcC', 'DwZNiXy5Daz', 'FHw1NKy0PWY', 'eQtZaLIO3XU', 'na3ZJRtjpGH', 'HkBG3DVELBM', 'sKBh0kazOCk', 'AAkZm4ZxFw7', 'ENRjVGxVL6l', 'aBaYLJryaMr'))and trackedentityinstanceid in (select trackedentityattributeid from trackedentityattribute where valuetype like 'PHONE_NUMBER'); 
 x trackedentityattributevalue;
 i integer := 1;
BEGIN
 OPEN c;
 LOOP
 FETCH c INTO x;
 EXIT WHEN NOT FOUND;
 UPDATE trackedentityattributevalue SET value = '+100001' || i WHERE CURRENT OF c;
 i := i + 1;
END LOOP;
END;$$;;
;DO
$$DECLARE
 c CURSOR FOR SELECT * FROM trackedentityattributevalue where trackedentityinstanceid 
in ( select ps.trackedentityinstanceid  from programinstance ps 
inner join program p on p.programid=ps.programid 
where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij')) and trackedentityinstanceid in 
(select trackedentityinstanceid from trackedentityinstance where uid in ('oTvXfEywjT3', 'n8E6WIyAwcC', 'DwZNiXy5Daz', 'FHw1NKy0PWY', 'eQtZaLIO3XU', 'na3ZJRtjpGH', 'HkBG3DVELBM', 'sKBh0kazOCk', 'AAkZm4ZxFw7', 'ENRjVGxVL6l', 'aBaYLJryaMr'))and trackedentityinstanceid in (select trackedentityattributeid from trackedentityattribute where valuetype like 'PHONE_NUMBER'); 
 x trackedentityattributevalue;
 i integer := 1;
BEGIN
 OPEN c;
 LOOP
 FETCH c INTO x;
 EXIT WHEN NOT FOUND;
 UPDATE trackedentityattributevalue SET value = '+100001' || i WHERE CURRENT OF c;
 i := i + 1;
END LOOP;
END;$$;;
---anonimize values 
;DO
$$DECLARE
 c CURSOR FOR SELECT * FROM trackedentityattributevalue where trackedentityinstanceid 
in ( select ps.trackedentityinstanceid  from programinstance ps 
inner join program p on p.programid=ps.programid 
where p.uid in ('uGCVVme3C4e', 'NHy39qEl1bc', 'KHDErSOFmy5', 'dIr4OtNcvMw', 'HnA4SUOaTij')) and trackedentityinstanceid in 
(select trackedentityinstanceid from trackedentityinstance where uid in ('oTvXfEywjT3', 'n8E6WIyAwcC', 'DwZNiXy5Daz', 'FHw1NKy0PWY', 'eQtZaLIO3XU', 'na3ZJRtjpGH', 'HkBG3DVELBM', 'sKBh0kazOCk', 'AAkZm4ZxFw7', 'ENRjVGxVL6l', 'aBaYLJryaMr')); 
 x trackedentityattributevalue;
 i integer := 1;
BEGIN
 OPEN c;
 LOOP
 FETCH c INTO x;
 EXIT WHEN NOT FOUND;
 UPDATE trackedentityattributevalue SET value = 'value' || i WHERE CURRENT OF c;
 i := i + 1;
END LOOP;
END;$$;;
--anonymize events
--remove all events
update programinstance set geometry=null, organisationunitid=(select organisationunitid from organisationunit ORDER BY RANDOM() limit 1) where programinstanceid in ( select psi.programinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('vFcxda6dJyT', 'RS6DH7eJJMZ', 'i5JSf4ffFl2', 'gxXvKE74vfQ', 'AODL0NZqmGx', 'MECZlaC9Ef6', 'JOwDQ193x2T', 'ela4dpipbEm', 'fQTmlJy1rLT', 'TFTLPseQEgi', 'uYKG1KOUIy1', 'h1KVXwrpKKf', 'dBAcTWcDpbO', 'NCGFNCiONAq', 'a7ygv0UrrSK', 'AOGxHgdhbYD', 'k3pL2hPUqQi', 'Jd8gnEIt8uT', 'nk0PS9gG8dy', 'EwH68ZzyDRk', 'Mvj9zd9l5g2', 'NVUlJzIakuO', 'IPEvFBRqJjW', 'w9hSFsNr3Vh', 'XQl1AKLPgy0', 'pvYIJL19r6G', 'qdlYvVgUjU7', 'wlWD2hWVghi', 'z6skqIipb47', 't1Yjgl9MeOE', 'CVh71SDylDD', 'M5pXkRoE62G', 'K45hjkzs0WX'));
update programstageinstance set geometry=null, organisationunitid=(select organisationunitid from organisationunit ORDER BY RANDOM() limit 1) where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('vFcxda6dJyT', 'RS6DH7eJJMZ', 'i5JSf4ffFl2', 'gxXvKE74vfQ', 'AODL0NZqmGx', 'MECZlaC9Ef6', 'JOwDQ193x2T', 'ela4dpipbEm', 'fQTmlJy1rLT', 'TFTLPseQEgi', 'uYKG1KOUIy1', 'h1KVXwrpKKf', 'dBAcTWcDpbO', 'NCGFNCiONAq', 'a7ygv0UrrSK', 'AOGxHgdhbYD', 'k3pL2hPUqQi', 'Jd8gnEIt8uT', 'nk0PS9gG8dy', 'EwH68ZzyDRk', 'Mvj9zd9l5g2', 'NVUlJzIakuO', 'IPEvFBRqJjW', 'w9hSFsNr3Vh', 'XQl1AKLPgy0', 'pvYIJL19r6G', 'qdlYvVgUjU7', 'wlWD2hWVghi', 'z6skqIipb47', 't1Yjgl9MeOE', 'CVh71SDylDD', 'M5pXkRoE62G', 'K45hjkzs0WX'));
--remove datasets
delete from datavalue where dataelementid in (select dataelementid from datasetelement where datasetid in ( select datasetid from dataset where uid in ('NePI9W0zSH5', 'UFlGxXoBrLN', 'ZO0DQJePIEH', 'Psf9CW4BSHM', 'Uc3j0vpsfSB', 'LdQ3CckNpeQ', 'tnek2LjfuIm', 'zna8KfLMXn4', 'XBgvNrxpcDC', 'WHPEpoVDFFv', 'SAV16xEdCZW', 'AAYgHGENgbF', 'ZhvE3MziQkC', 'yOf6XrrS3uy', 'NKWbkXyfO5F', 'p0NhuIUoeST', 'oVxjBKA1Yzu', 'deKCGAGoEHz', 'S1UMweeoPsi', 'fdBM4sWSuPR', 'SHw2zOysJ1R', 's3iaozBY0dv', 'JP4bMwvJ6oU', 'U5ejGQdX4Ih'))) and  dataelementid in (select dataelementid from datasetelement where datasetid in ( select datasetid from dataset where uid in ('tnek2LjfuIm', 'zna8KfLMXn4', 'XBgvNrxpcDC', 'WHPEpoVDFFv', 'SAV16xEdCZW', 'AAYgHGENgbF', 'NKWbkXyfO5F', 'oVxjBKA1Yzu', 'S1UMweeoPsi', 's3iaozBY0dv', 'JP4bMwvJ6oU', 'U5ejGQdX4Ih'))) ;
--CSY
--remove all tracker
delete from trackedentitydatavalueaudit where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('YGa3BmrwwiU'));
delete from programstageinstancecomments where programstageinstanceid in ( select programstageinstanceid from programstageinstance where programstageid in (select programstageid from programstage where programid in (select programid from program where uid in ('YGa3BmrwwiU'))));
delete from trackedentityattributevalue where trackedentityinstanceid in ( select trackedentityinstanceid from programinstance where programid in(select programid from program where uid in ('YGa3BmrwwiU')));
delete from trackedentityattributevalueaudit where trackedentityinstanceid in ( select trackedentityinstanceid from programinstance where programid in(select programid from program where uid in ('YGa3BmrwwiU')));
delete from programstageinstance where programstageid in (select programstageid from programstage where programid in (select programid from program where uid in ('YGa3BmrwwiU')));
delete from programstageinstance where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('YGa3BmrwwiU'));
create view tei_to_remove as select trackedentityinstanceid "teiid" from programinstance where programid in (select programid from program where uid in ('YGa3BmrwwiU'));
delete from programinstance where programid in (select programid from program where uid in ('YGa3BmrwwiU'));
delete from programinstance where trackedentityinstanceid in ( select * from tei_to_remove);
delete from trackedentityinstance where trackedentityinstanceid in ( select * from tei_to_remove);
delete from trackedentityprogramowner where trackedentityinstanceid in ( select * from tei_to_remove);
drop view tei_to_remove ;
--remove tracker finish
--remove all events
delete from trackedentitydatavalueaudit where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('auqdJ66DqAT', 'BslciOZ3Rvs', 'gYhhLQlqduE', 'nmXOLkibWJc'));
delete from programstageinstancecomments where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('auqdJ66DqAT', 'BslciOZ3Rvs', 'gYhhLQlqduE', 'nmXOLkibWJc'));
delete from programstageinstance where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('auqdJ66DqAT', 'BslciOZ3Rvs', 'gYhhLQlqduE', 'nmXOLkibWJc'));
--GHP
--remove all events
delete from trackedentitydatavalueaudit where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('azxjVmQLicj', 'cTzRXZGNvqz'));
delete from programstageinstancecomments where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('azxjVmQLicj', 'cTzRXZGNvqz'));
delete from programstageinstance where programstageinstanceid in ( select psi.programstageinstanceid  from programstageinstance psi inner join programstage ps on ps.programstageid=psi.programstageid inner join program p on p.programid=ps.programid where p.uid in ('azxjVmQLicj', 'cTzRXZGNvqz'));
--remove all datasets
delete from datavalueaudit where dataelementid in (select dataelementid from datasetelement where datasetid in (select datasetid from dataset where uid in ('jfawDJZ5fOX', 'ITKN1N2pPHp', 'KJbR0F9jUbf')));
delete from datavalue where dataelementid in (select dataelementid from datasetelement where datasetid in (select datasetid from dataset where uid in ('jfawDJZ5fOX', 'ITKN1N2pPHp', 'KJbR0F9jUbf')));
--GMP_ENTO
--GMP_EPI
--remove all datasets
delete from datavalueaudit where dataelementid in (select dataelementid from datasetelement where datasetid in (select datasetid from dataset where uid in ('bNJzkNJv0Yg', 'qDd74Hfk2Dc', 'qNtxTrp56wV', 'Cm6vhZilyPa', 'iENTl91i0Hg', 'O34y2Kyxx6P', 'ctDGeFX3fNZ', 'tZyUewB5zBf', 'VEM58nY22sO', 'VTVvoKniNhi', 'zyZLeSbJxqR', 'w9sYDdAm1bx', 'wBSMl47uQib', 'alvBxSxuorK', 'SqN2upmg2Im', 'SqJAH6Pu3Cs', 'Ai48B5k6hwb', 'M05iAqd6ZFU', 'PWCUb3Se1Ie', 'IXuqhJzEYP9', 'I1Tn68LFq5Y')));
delete from datavalue where dataelementid in (select dataelementid from datasetelement where datasetid in (select datasetid from dataset where uid in ('bNJzkNJv0Yg', 'qDd74Hfk2Dc', 'qNtxTrp56wV', 'Cm6vhZilyPa', 'iENTl91i0Hg', 'O34y2Kyxx6P', 'ctDGeFX3fNZ', 'tZyUewB5zBf', 'VEM58nY22sO', 'VTVvoKniNhi', 'zyZLeSbJxqR', 'w9sYDdAm1bx', 'wBSMl47uQib', 'alvBxSxuorK', 'SqN2upmg2Im', 'SqJAH6Pu3Cs', 'Ai48B5k6hwb', 'M05iAqd6ZFU', 'PWCUb3Se1Ie', 'IXuqhJzEYP9', 'I1Tn68LFq5Y')));
--HWF
